import { DatabaseSync } from 'node:sqlite';
import { mkdtempSync, readFileSync, readdirSync, writeFileSync, existsSync, symlinkSync, unlinkSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createBackup, verifyBackup, restoreBackup } from '../backup.mjs';

const base=mkdtempSync(path.join(os.tmpdir(),'rei-backup-'));
const source=path.join(base,'data');
const { mkdirSync }=await import('node:fs');mkdirSync(source);
const db=new DatabaseSync(path.join(source,'rei.sqlite'));
db.exec('PRAGMA journal_mode=WAL; CREATE TABLE sample(value TEXT); INSERT INTO sample VALUES (\'saved\')');
writeFileSync(path.join(source,'chatwork.key'),'test-key');
writeFileSync(path.join(source,'mcp-sync.json.tmp'),'reconcile-before-use');
writeFileSync(path.join(source,'pending-results.json'),'[{"taskId":"pending-report"}]');
writeFileSync(path.join(source,'pending-results.json.tmp'),'[{"taskId":"possibly-newer-report"}]');
writeFileSync(path.join(source,'owner-credentials.txt'),'excluded');
const folder=await createBackup(source,path.join(base,'backups'));
assert.equal(readdirSync(path.join(base,'backups')).some(name=>name.startsWith('.partial-')),false);
const invalidSource=path.join(base,'invalid-database');
mkdirSync(invalidSource);
writeFileSync(path.join(invalidSource,'rei.sqlite'),'not a SQLite database');
const beforeInvalidDatabase=readdirSync(path.join(base,'backups')).sort();
await assert.rejects(()=>createBackup(invalidSource,path.join(base,'backups')));
assert.deepEqual(readdirSync(path.join(base,'backups')).sort(),beforeInvalidDatabase);
const linkedDatabase=path.join(base,'linked-database');
mkdirSync(linkedDatabase);
symlinkSync(path.join(source,'rei.sqlite'),path.join(linkedDatabase,'rei.sqlite'),'file');
await assert.rejects(()=>createBackup(linkedDatabase,path.join(base,'backups')),/バックアップ対象が通常のファイルではありません: rei.sqlite/);
assert.deepEqual(verifyBackup(folder).files,['rei.sqlite','chatwork.key','mcp-sync.json.tmp','pending-results.json','pending-results.json.tmp']);
assert.equal(existsSync(path.join(folder,'owner-credentials.txt')),false);
const destination=path.join(base,'restored');
restoreBackup(folder,destination);
assert.equal(readdirSync(base).some(name=>name.startsWith('.partial-restore-')),false);
const emptyDestination=path.join(base,'empty-restored');
mkdirSync(emptyDestination);
assert.equal(restoreBackup(folder,emptyDestination),emptyDestination);
assert.equal(readFileSync(path.join(emptyDestination,'chatwork.key'),'utf8'),'test-key');
const restored=new DatabaseSync(path.join(destination,'rei.sqlite'),{readOnly:true});
assert.equal(restored.prepare('SELECT value FROM sample').get().value,'saved');
restored.close();db.close();
assert.equal(readFileSync(path.join(destination,'chatwork.key'),'utf8'),'test-key');
assert.equal(readFileSync(path.join(destination,'mcp-sync.json.tmp'),'utf8'),'reconcile-before-use');
assert.equal(readFileSync(path.join(destination,'pending-results.json'),'utf8'),'[{"taskId":"pending-report"}]');
assert.equal(readFileSync(path.join(destination,'pending-results.json.tmp'),'utf8'),'[{"taskId":"possibly-newer-report"}]');
assert.throws(()=>restoreBackup(folder,destination),/空のフォルダ/);
const redirected=path.join(base,'redirected');
mkdirSync(redirected);
const link=path.join(base,'linked-restored');
symlinkSync(redirected,link,'dir');
assert.throws(()=>restoreBackup(folder,link),/空のフォルダ/);
await assert.rejects(()=>createBackup(source,link),/通常のフォルダ/);
assert.equal(existsSync(path.join(redirected,'rei.sqlite')),false);
const linkedBackup=await createBackup(source,path.join(base,'backups'));
unlinkSync(path.join(linkedBackup,'rei.sqlite'));
symlinkSync(path.join(source,'rei.sqlite'),path.join(linkedBackup,'rei.sqlite'),'file');
assert.throws(()=>verifyBackup(linkedBackup),/検証に失敗しました: rei.sqlite/);
symlinkSync(path.join(source,'owner-credentials.txt'),path.join(source,'connector.json'),'file');
const beforeFailedBackup=readdirSync(path.join(base,'backups')).sort();
await assert.rejects(()=>createBackup(source,path.join(base,'backups')),/バックアップ対象が通常のファイルではありません: connector.json/);
assert.deepEqual(readdirSync(path.join(base,'backups')).sort(),beforeFailedBackup);
writeFileSync(path.join(folder,'chatwork.key'),'tampered');
assert.throws(()=>verifyBackup(folder),/検証に失敗/);
const refusedDestination=path.join(base,'refused-restored');
assert.throws(()=>restoreBackup(folder,refusedDestination),/検証に失敗/);
assert.equal(existsSync(refusedDestination),false);
console.log('PASS online backup, integrity, restore, tamper detection');
