import { DatabaseSync } from 'node:sqlite';
import { mkdtempSync, readFileSync, writeFileSync, existsSync, symlinkSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createBackup, verifyBackup, restoreBackup } from '../backup.mjs';

const base=mkdtempSync(path.join(os.tmpdir(),'rei-backup-'));
const source=path.join(base,'data');
const { mkdirSync }=await import('node:fs');mkdirSync(source);
const db=new DatabaseSync(path.join(source,'rei.sqlite'));
db.exec('PRAGMA journal_mode=WAL; CREATE TABLE sample(value TEXT); INSERT INTO sample VALUES (\'saved\')');
writeFileSync(path.join(source,'chatwork.key'),'test-key');
writeFileSync(path.join(source,'pending-results.json'),'[{"taskId":"pending-report"}]');
writeFileSync(path.join(source,'pending-results.json.tmp'),'[{"taskId":"possibly-newer-report"}]');
writeFileSync(path.join(source,'owner-credentials.txt'),'excluded');
const folder=await createBackup(source,path.join(base,'backups'));
assert.deepEqual(verifyBackup(folder).files,['rei.sqlite','chatwork.key','pending-results.json','pending-results.json.tmp']);
assert.equal(existsSync(path.join(folder,'owner-credentials.txt')),false);
const destination=path.join(base,'restored');
restoreBackup(folder,destination);
const restored=new DatabaseSync(path.join(destination,'rei.sqlite'),{readOnly:true});
assert.equal(restored.prepare('SELECT value FROM sample').get().value,'saved');
restored.close();db.close();
assert.equal(readFileSync(path.join(destination,'chatwork.key'),'utf8'),'test-key');
assert.equal(readFileSync(path.join(destination,'pending-results.json'),'utf8'),'[{"taskId":"pending-report"}]');
assert.equal(readFileSync(path.join(destination,'pending-results.json.tmp'),'utf8'),'[{"taskId":"possibly-newer-report"}]');
assert.throws(()=>restoreBackup(folder,destination),/空のフォルダ/);
const redirected=path.join(base,'redirected');
mkdirSync(redirected);
const link=path.join(base,'linked-restored');
symlinkSync(redirected,link,'dir');
assert.throws(()=>restoreBackup(folder,link),/空のフォルダ/);
await assert.rejects(()=>createBackup(source,link),/通常のフォルダ/);
assert.equal(existsSync(path.join(redirected,'rei.sqlite')),false);
writeFileSync(path.join(folder,'chatwork.key'),'tampered');
assert.throws(()=>verifyBackup(folder),/検証に失敗/);
console.log('PASS online backup, integrity, restore, tamper detection');
