import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';

const root=path.join(path.dirname(fileURLToPath(import.meta.url)),'..');
const config=path.join(mkdtempSync(path.join(os.tmpdir(),'rei-connector-guard-')),'connector.json');
const original='{"hub":"http://127.0.0.1:4178","token":"existing-token","agent":"main"}';
writeFileSync(config,original);
const result=spawnSync(process.execPath,['connector.mjs','join','http://127.0.0.1:4178'],{cwd:root,env:{...process.env,REI_CONNECTOR_CONFIG:config},encoding:'utf8',timeout:10000});
assert.notEqual(result.status,0);
assert.match(result.stderr,/既にREIの接続設定/);
assert.equal(readFileSync(config,'utf8'),original);
const manual=spawnSync(process.execPath,['connector.mjs','setup'],{cwd:root,env:{...process.env,REI_CONNECTOR_CONFIG:config},input:'http://127.0.0.1:4178\nnew-token\nrei\n',encoding:'utf8',timeout:10000});
assert.notEqual(manual.status,0);
assert.match(manual.stderr,/既にREIの接続設定/);
assert.equal(readFileSync(config,'utf8'),original);
const restoredData=mkdtempSync(path.join(os.tmpdir(),'rei-restored-'));
writeFileSync(path.join(restoredData,'connector.json'),JSON.stringify({hub:'http://example.com',token:'restored-token',agent:'rei'}));
const restored=spawnSync(process.execPath,['connector.mjs','--once'],{cwd:root,env:{...process.env,REI_CONNECTOR_CONFIG:'',REI_DATA_DIR:restoredData},encoding:'utf8',timeout:10000});
assert.notEqual(restored.status,0);
assert.match(restored.stderr,/HubはHTTPS/);
const damagedDir=mkdtempSync(path.join(os.tmpdir(),'rei-damaged-results-'));
writeFileSync(path.join(damagedDir,'connector.json'),JSON.stringify({hub:'http://127.0.0.1:4181',token:'test-token',agent:'rei'}));
const damagedPath=path.join(damagedDir,'pending-results.json');
writeFileSync(damagedPath,'[{"taskId":"unfinished"');
const damaged=spawnSync(process.execPath,['connector.mjs','--once'],{cwd:root,env:{...process.env,REI_CONNECTOR_CONFIG:path.join(damagedDir,'connector.json')},encoding:'utf8',timeout:10000});
assert.notEqual(damaged.status,0);
assert.match(damaged.stderr,/送信待ち結果を読み取れません/);
assert.equal(readFileSync(damagedPath,'utf8'),'[{"taskId":"unfinished"');
writeFileSync(damagedPath,'[]');
writeFileSync(`${damagedPath}.tmp`,'[{"taskId":"possibly-saved"}]');
const interrupted=spawnSync(process.execPath,['connector.mjs','--once'],{cwd:root,env:{...process.env,REI_CONNECTOR_CONFIG:path.join(damagedDir,'connector.json')},encoding:'utf8',timeout:10000});
assert.notEqual(interrupted.status,0);
assert.match(interrupted.stderr,/未完了の結果保存ファイル/);
assert.equal(readFileSync(`${damagedPath}.tmp`,'utf8'),'[{"taskId":"possibly-saved"}]');
console.log('PASS connector configuration and damaged pending results are preserved');
