import assert from 'node:assert/strict';
import {ConversationMcp} from '../conversation-mcp.mjs';
const integration={name:'rei_0123456789ab',url:'https://mcp.synapse-connect.ai/mcp'};
const client=new ConversationMcp('.');
let release,opened=0,disposed=0;
const gate=new Promise(resolve=>{release=resolve;});
client.open=async value=>{opened++;await gate;client.signature=value.name;return client.runtime={dispose:async()=>{disposed++;}};};
const connections=[client.connect(integration),client.connect(integration),client.connect(integration)];
assert.equal(opened,1);
let closed=false;const closing=client.close().then(()=>{closed=true;});
await Promise.resolve();assert.equal(closed,false);release();
const runtimes=await Promise.all(connections);assert.equal(new Set(runtimes).size,1);
await closing;assert.equal(disposed,1);assert.equal(client.runtime,null);
const retry=new ConversationMcp('.');let attempts=0;
retry.open=async value=>{attempts++;await Promise.resolve();if(attempts===1)throw Error('fixture');retry.signature=value.name;return retry.runtime={dispose:async()=>{}};};
const failures=await Promise.allSettled([retry.connect(integration),retry.connect(integration)]);
assert.ok(failures.every(value=>value.status==='rejected'));assert.equal(attempts,1);
assert.ok(await retry.connect(integration));assert.equal(attempts,2);await retry.close();
console.log('PASS parallel MCP initialization shares one runtime, close waits, failed initialization can retry');
const history=new ConversationMcp('.');let sent;
history.connect=async()=>({callTool:async(name,tool,args)=>{sent=args;return {structuredContent:{episodes:[],coverage:{complete:true}}};}});
await assert.rejects(history.call(integration,'get_updates',{group_ids:['g'],group_id:'g'}),/栞/);
await assert.rejects(history.call(integration,'get_updates',{group_ids:['g'],group_id:'outside',advance:false}),/選択範囲/);
await history.call(integration,'get_updates',{group_ids:['g'],group_id:'g',advance:false,start:'beginning'});
assert.equal(sent.advance,false);assert.equal(sent.group_ids,undefined);
console.log('PASS update reads require explicit readonly mode and selected group; no bookmark writes');

const catalogs=new ConversationMcp('.');let finishCatalog,catalogCalls=0;
const runtime={callTool:async()=>{catalogCalls++;return new Promise(r=>finishCatalog=r);}};
catalogs.connect=async()=>runtime;
const simultaneous=[catalogs.catalog(integration),catalogs.catalog(integration),catalogs.catalog(integration)];
await new Promise(setImmediate);assert.equal(catalogCalls,1);
finishCatalog({structuredContent:{groups:[{group_id:'fixture'}]}});
const shared=await Promise.all(simultaneous);shared[0].structuredContent.groups.length=0;
assert.deepEqual(shared.map(r=>r.reiMcpTiming.joined),[false,true,true]);
for(const result of shared){assert.deepEqual(Object.keys(result.reiMcpTiming).sort(),['connectMs','joined','totalMs','waitMs']);for(const key of ['connectMs','waitMs','totalMs'])assert.ok(Number.isFinite(result.reiMcpTiming[key])&&result.reiMcpTiming[key]>=0);}
assert.equal(shared[1].structuredContent.groups.length,1,'callers cannot mutate another permission result');
const freshCatalog=catalogs.catalog(integration);await new Promise(setImmediate);assert.equal(catalogCalls,2,'subsequent permission check must fetch fresh');finishCatalog({structuredContent:{groups:[]}});assert.equal((await freshCatalog).structuredContent.groups.length,0);
let rejectedCalls=0;runtime.callTool=async()=>{rejectedCalls++;throw Error('catalog failure');};
assert.ok((await Promise.allSettled([catalogs.catalog(integration),catalogs.catalog(integration)])).every(r=>r.status==='rejected'));assert.equal(rejectedCalls,1);
await assert.rejects(catalogs.catalog(integration),/catalog failure/);assert.equal(rejectedCalls,2,'failure must not be retained');
let separateCalls=0;runtime.callTool=async()=>({call:++separateCalls});
await Promise.all([catalogs.catalog(integration),catalogs.catalog({...integration,name:'rei_abcdef012345'})]);assert.equal(separateCalls,2,'integrations never share permission catalogs');
const replaced={callTool:async()=>({runtime:'new'})};catalogs.connect=async()=>replaced;
assert.equal((await catalogs.catalog(integration)).runtime,'new','replacement authenticated runtime has a separate flight');
let finishOld;runtime.callTool=async()=>new Promise(r=>finishOld=r);catalogs.connect=async()=>runtime;
const oldFlight=catalogs.catalog(integration);await new Promise(setImmediate);catalogs.connect=async()=>replaced;
assert.equal((await catalogs.catalog(integration)).runtime,'new','a new authentication runtime cannot join an unfinished old request');
finishOld({runtime:'old'});assert.equal((await oldFlight).runtime,'old');
console.log('PASS only simultaneous catalogs coalesce; completion, failure, integration and runtime remain fresh and isolated');
