import assert from 'node:assert/strict';
import {ConversationMcp} from '../conversation-mcp.mjs';
const integration={name:'rei_0123456789ab',url:'https://mcp.synapse-connect.ai/mcp'};
const client=new ConversationMcp('.');
let release,opened=0,disposed=0;
const gate=new Promise(resolve=>{release=resolve;});
client.open=async value=>{opened++;await gate;client.signature=value.name;return client.runtime={dispose:async()=>{disposed++;}};};
const connections=[client.connect(integration),client.connect(integration),client.connect(integration)];
assert.equal(opened,1);
let closed=false;const closing=client.close().then(()=>{closed=true;});
await Promise.resolve();assert.equal(closed,false);release();
const runtimes=await Promise.all(connections);assert.equal(new Set(runtimes).size,1);
await closing;assert.equal(disposed,1);assert.equal(client.runtime,null);
const retry=new ConversationMcp('.');let attempts=0;
retry.open=async value=>{attempts++;await Promise.resolve();if(attempts===1)throw Error('fixture');retry.signature=value.name;return retry.runtime={dispose:async()=>{}};};
const failures=await Promise.allSettled([retry.connect(integration),retry.connect(integration)]);
assert.ok(failures.every(value=>value.status==='rejected'));assert.equal(attempts,1);
assert.ok(await retry.connect(integration));assert.equal(attempts,2);await retry.close();
console.log('PASS parallel MCP initialization shares one runtime, close waits, failed initialization can retry');
const history=new ConversationMcp('.');let sent;
history.connect=async()=>({callTool:async(name,tool,args)=>{sent=args;return {structuredContent:{episodes:[],coverage:{complete:true}}};}});
await assert.rejects(history.call(integration,'get_updates',{group_ids:['g'],group_id:'g'}),/栞/);
await assert.rejects(history.call(integration,'get_updates',{group_ids:['g'],group_id:'outside',advance:false}),/選択範囲/);
await history.call(integration,'get_updates',{group_ids:['g'],group_id:'g',advance:false,start:'beginning'});
assert.equal(sent.advance,false);assert.equal(sent.group_ids,undefined);
console.log('PASS update reads require explicit readonly mode and selected group; no bookmark writes');
