import { spawn } from 'node:child_process';
import { createServer } from 'node:http';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, chmodSync, unlinkSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';

const root=path.join(path.dirname(fileURLToPath(import.meta.url)),'..');
const currentVersion=JSON.parse(readFileSync(path.join(root,'package.json'),'utf8')).version;
const dir=mkdtempSync(path.join(os.tmpdir(),'rei-doctor-'));
const bin=path.join(dir,'bin');mkdirSync(bin);
const fake=`#!/usr/bin/env node
if(process.argv.includes('--version'))console.log('1.0');
else if(process.argv.includes('models'))console.log(JSON.stringify({resolvedDefault:'openai/test',auth:{missingProvidersInUse:process.env.REI_TEST_NO_MODEL==='1'?['openai']:[]}}));
else if(process.argv.includes('list'))console.log(JSON.stringify([{id:'rei'}]));
else if(process.argv.includes('config'))console.log(JSON.stringify({list:[{id:'rei',tools:{deny:process.env.REI_TEST_UNSAFE==='1'?[]:['message','sessions_send','gateway']}}]}));
else process.exit(2);
`;
for(const name of ['openclaw','openclaw.mjs']){const file=path.join(bin,name);writeFileSync(file,fake);chmodSync(file,0o755);}
let hubVersion=currentVersion;
const server=createServer((req,res)=>{const status=new URL(req.url,'http://localhost').searchParams.get('route')==='connector/status';const ok=!status||req.headers.authorization==='Bearer secret-do-not-print';res.writeHead(ok?200:401,{'content-type':'application/json'});res.end(JSON.stringify({ok,hubVersion}));});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const config=path.join(dir,'connector.json');
const env={...process.env,PATH:`${bin}${path.delimiter}${process.env.PATH}`,REI_OPENCLAW_ENTRY:path.join(bin,'openclaw.mjs'),REI_CONNECTOR_CONFIG:config};
async function doctor() {
  const child=spawn(process.execPath,['doctor.mjs'],{cwd:root,env,stdio:['ignore','pipe','pipe']});
  let output='';child.stdout.on('data',chunk=>output+=chunk);child.stderr.on('data',chunk=>output+=chunk);
  const code=await new Promise(resolve=>child.on('close',resolve));
  return {code,output};
}
try {
  writeFileSync(config,JSON.stringify({hub:`http://127.0.0.1:${server.address().port}`,token:'secret-do-not-print',agent:'rei'}));
  const healthy=await doctor();
  assert.equal(healthy.code,0,healthy.output);
  assert.match(healthy.output,/中心PCのREIに接続できます/);
  assert.match(healthy.output,/端末トークンは中心PCで有効です/);
  assert.match(healthy.output,/REIの版は一致しています/);
  assert.match(healthy.output,/直接送信・管理操作は制限されています/);
  assert.match(healthy.output,/モデル設定を確認しました/);
  assert.match(healthy.output,/実行期限は1800秒/);
  assert.doesNotMatch(healthy.output,/secret-do-not-print/);
  env.REI_JOB_TIMEOUT_SECONDS='0';
  const invalidTimeout=await doctor();
  assert.equal(invalidTimeout.code,1);
  assert.match(invalidTimeout.output,/実行期限の設定を確認してください/);
  delete env.REI_JOB_TIMEOUT_SECONDS;
  env.REI_TEST_NO_MODEL='1';
  const missingModel=await doctor();
  assert.equal(missingModel.code,1);
  assert.match(missingModel.output,/モデル認証を確認してください/);
  delete env.REI_TEST_NO_MODEL;
  env.REI_TEST_UNSAFE='1';
  const unsafe=await doctor();
  assert.equal(unsafe.code,1);
  assert.match(unsafe.output,/直接送信・管理操作の制限を確認してください/);
  delete env.REI_TEST_UNSAFE;
  hubVersion='0.3.0';
  const outdated=await doctor();
  assert.equal(outdated.code,1);
  assert.match(outdated.output,/REIの版が異なります/);
  hubVersion=currentVersion;
  writeFileSync(config,JSON.stringify({hub:`http://127.0.0.1:${server.address().port}`,token:'revoked-token',agent:'rei'}));
  const revoked=await doctor();
  assert.equal(revoked.code,1);
  assert.match(revoked.output,/要確認  端末トークンが無効です/);
  assert.doesNotMatch(revoked.output,/revoked-token/);
  writeFileSync(config,JSON.stringify({hub:`http://127.0.0.1:${server.address().port}`,token:'secret-do-not-print',agent:'rei'}));
  writeFileSync(path.join(dir,'pending-results.json.tmp'),'unfinished');
  const interrupted=await doctor();
  assert.equal(interrupted.code,1);
  assert.match(interrupted.output,/保存途中ファイル/);
  unlinkSync(path.join(dir,'pending-results.json.tmp'));
  writeFileSync(path.join(dir,'pending-results.json'),JSON.stringify([{taskId:'task-1',leaseId:'lease-1',success:true,result:'saved',error:''}]));
  const queued=await doctor();
  assert.equal(queued.code,1);
  assert.match(queued.output,/送信待ち結果 1件/);
  writeFileSync(path.join(dir,'pending-results.json'),'[{}]');
  const damaged=await doctor();
  assert.equal(damaged.code,1);
  assert.match(damaged.output,/送信待ち結果の形式が正しくありません/);
  unlinkSync(path.join(dir,'pending-results.json'));
  unlinkSync(config);
  const missing=await doctor();
  assert.equal(missing.code,1);
  assert.match(missing.output,/接続設定がありません/);
  console.log('PASS connector doctor checks prerequisites without showing tokens');
} finally {server.close();}
