import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { createServer } from 'node:http';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, utimesSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { openStorage, one, run } from '../storage.mjs';
import { createBackup } from '../backup.mjs';

const root=path.join(path.dirname(fileURLToPath(import.meta.url)),'..');
const version=JSON.parse(readFileSync(path.join(root,'package.json'),'utf8')).version;
const data=mkdtempSync(path.join(os.tmpdir(),'rei-hub-doctor-'));
process.env.REI_DATA_DIR=data;
const db=openStorage(data);
let servedVersion=version;
const server=createServer((request,response)=>{
  response.writeHead(200,{'content-type':'application/json'});
  response.end(JSON.stringify({needsSetup:!one(db,"SELECT id FROM users WHERE role='owner' LIMIT 1"),version:servedVersion}));
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
async function diagnose() {
  const child=spawn(process.execPath,['doctor-hub.mjs'],{cwd:root,env:{...process.env,REI_DATA_DIR:data,REI_PORT:String(server.address().port)},stdio:['ignore','pipe','pipe']});
  let output='';
  child.stdout.on('data',chunk=>output+=chunk);
  child.stderr.on('data',chunk=>output+=chunk);
  const code=await new Promise(resolve=>child.on('close',resolve));
  return {code,output};
}
try {
  const initial=await diagnose();
  assert.equal(initial.code,1);
  assert.match(initial.output,/所有者の初回登録を完了してください/);
  run(db,"INSERT INTO users(id,username,salt,digest,role) VALUES(?,?,?,?,?)",'owner','owner','salt','digest','owner');
  const unprotected=await diagnose();
  assert.equal(unprotected.code,1);
  assert.match(unprotected.output,/有効なバックアップを確認できません/);
  const backup=await createBackup(data);
  const healthy=await diagnose();
  assert.equal(healthy.code,0,healthy.output);
  assert.match(healthy.output,/最新のバックアップを検証しました/);
  process.env.REI_BACKUP_DIR=path.join(data,'external-backups');
  mkdirSync(process.env.REI_BACKUP_DIR);
  await createBackup(data);
  const external=await diagnose();
  assert.equal(external.code,0,external.output);
  process.env.REI_BACKUP_DIR='relative-backups';
  const invalidDirectory=await diagnose();
  assert.equal(invalidDirectory.code,1,invalidDirectory.output);
  assert.match(invalidDirectory.output,/REI_BACKUP_DIRには絶対パス/);
  process.env.REI_BACKUP_DIR=path.join(data,'missing-drive','backups');
  const missingDrive=await diagnose();
  assert.equal(missingDrive.code,1,missingDrive.output);
  assert.match(missingDrive.output,/REI_BACKUP_DIRの保存先が見つかりません/);
  delete process.env.REI_BACKUP_DIR;
  servedVersion='older';
  const outdated=await diagnose();
  assert.equal(outdated.code,1,outdated.output);
  assert.match(outdated.output,/起動中のREIがこのフォルダの版と異なります/);
  servedVersion=version;
  const interrupted=path.join(data,'backups','.partial-interrupted');
  mkdirSync(interrupted);
  const oldTime=new Date(Date.now()-2*3600000);
  utimesSync(interrupted,oldTime,oldTime);
  const incomplete=await diagnose();
  assert.equal(incomplete.code,1,incomplete.output);
  assert.match(incomplete.output,/中断したバックアップが1件/);
  rmSync(interrupted,{recursive:true});
  const manifestFile=path.join(backup,'manifest.json');
  const manifest=JSON.parse(readFileSync(manifestFile,'utf8'));
  manifest.createdAt=new Date(Date.now()-8*86400000).toISOString();
  writeFileSync(manifestFile,JSON.stringify(manifest));
  const old=await diagnose();
  assert.equal(old.code,1,old.output);
  assert.match(old.output,/8日前です/);
  writeFileSync(path.join(backup,'manifest.json'),'broken');
  const damaged=await diagnose();
  assert.equal(damaged.code,1);
  assert.match(damaged.output,/有効なバックアップを確認できません/);
  console.log('PASS Hub doctor checks setup and backup without changing data');
} finally {db.close();server.close();}
