import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { openStorage, one, run } from '../storage.mjs';
import { parseIntelligence, intelligencePrompt, knowledgeSettings, saveKnowledgeSettings } from '../intelligence.mjs';
import { queueKnowledge, scanKnowledgeIfDue } from '../knowledge-service.mjs';
import { claim, finishJob } from '../workflow.mjs';
const groups=[{id:'company',name:'会社共有'}];
const report={status:'answered',answer:'決定事項を確認しました。'.repeat(130),searchedGroups:['会社共有'],uncertainties:['一部の古い記録は未確認'],sources:[{groupId:'company',group:'会社共有',recordId:'episode-1',title:'決定事項',recordedAt:'2026-10-06T09:00:00+09:00',url:null}],suggestions:[{title:'資料を準備',reason:'決定に必要なため',sourceIds:['episode-1'],prompt:'資料の構成案を作成してください'}]};
const parsed=parseIntelligence(JSON.stringify(report),'scan',groups);
assert.ok(parsed);
assert.equal(parseIntelligence(JSON.stringify({...report,sources:[]}),'answer',groups),null);
assert.equal(parseIntelligence(JSON.stringify(report),'scan',[]),null);
assert.equal(parseIntelligence(JSON.stringify({...report,sources:[{...report.sources[0],groupId:'private'}]}),'answer',groups),null);
assert.equal(parseIntelligence(JSON.stringify({...report,sources:[{...report.sources[0],url:'https://example.org/source?token=secret'}]}),'answer',groups),null);
assert.equal(parseIntelligence(JSON.stringify({...report,suggestions:[{...report.suggestions[0],sourceIds:['invented']}]}),'scan',groups),null);
assert.equal(parseIntelligence(JSON.stringify({...report,status:'no_match'}),'scan',groups),null);
assert.ok(parseIntelligence(JSON.stringify({...report,status:'unavailable',sources:[],suggestions:[]}),'answer',groups));
assert.equal(parseIntelligence(JSON.stringify({...report,status:'catalog',sources:[],suggestions:[],groups:[{id:'private',name:'個人',visibility:'private'}]}),'catalog'),null);
assert.match(intelligencePrompt({knowledge_mode:'scan',knowledge_scope:JSON.stringify(groups),text:'次を確認'}),/preview.*get_episode/);
const dir=mkdtempSync(path.join(os.tmpdir(),'rei-intelligence-'));process.env.REI_DATA_DIR=dir;
let db=openStorage(dir);const time=Date.now(),version='test';
try {
  run(db,"INSERT INTO users(id,username,salt,digest,role) VALUES('owner','owner','salt','digest','owner')");
  run(db,"INSERT INTO devices(id,label,token_hash,version,last_seen,capabilities) VALUES('pc','test','hash',?,?,?)",version,time,JSON.stringify(['execution']));
  run(db,"INSERT INTO mcp_integrations(name,label,url,auth,device_id,created_at) VALUES('synapse','SynapseConnect','https://mcp.synapse-connect.ai/mcp','oauth','pc',?)",time);
  run(db,"INSERT INTO device_mcp_status(device_id,name,status,updated_at) VALUES('pc','synapse','configured',?)",time);
  assert.throws(()=>queueKnowledge(db,version,'answer','会社の予定は？','owner'),/共有グループ/);
  saveKnowledgeSettings(db,{enabled:true,intervalHours:6,groups},'owner',time);
  const task=queueKnowledge(db,version,'answer','会社の決定事項は？','owner');
  assert.equal(one(db,"SELECT COUNT(*) AS count FROM tasks WHERE parent_id=? AND kind='plan'",task.id).count,0);
  const device=one(db,"SELECT * FROM devices WHERE id='pc'");const job=claim(db,device,version);
  assert.equal(job.knowledge_mode,'answer');
  assert.deepEqual(JSON.parse(job.knowledge_scope),groups);
  const input={taskId:job.id,leaseId:job.lease_id,success:true,result:JSON.stringify(report)};
  assert.deepEqual(finishJob(db,device,input),{ok:true});
  assert.deepEqual(finishJob(db,device,input),{ok:true,alreadyRecorded:true});
  assert.equal(one(db,'SELECT status FROM tasks WHERE id=?',task.id).status,'completed');
  assert.ok(one(db,'SELECT result FROM tasks WHERE id=?',task.id).result.length>1000);
  assert.equal(one(db,"SELECT COUNT(*) AS count FROM tasks WHERE parent_id=? AND kind='human'",task.id).count,0);
  const bad=queueKnowledge(db,version,'answer','確認','owner');const badJob=claim(db,device,version);
  const invalid={taskId:badJob.id,leaseId:badJob.lease_id,success:true,result:JSON.stringify({...report,sources:[]})};
  finishJob(db,device,invalid);assert.equal(one(db,'SELECT status FROM tasks WHERE id=?',bad.id).status,'needs_review');
  assert.deepEqual(finishJob(db,device,invalid),{ok:true,alreadyRecorded:true});
  assert.equal(scanKnowledgeIfDue(db,version,time),null);
  const due=time+6*3600000;run(db,"UPDATE devices SET last_seen=? WHERE id='pc'",due);
  const scan=scanKnowledgeIfDue(db,version,due);assert.ok(scan);
  assert.equal(scanKnowledgeIfDue(db,version,due),null);
  db.close();db=openStorage(dir);
  assert.equal(scanKnowledgeIfDue(db,version,due),null);
  assert.equal(knowledgeSettings(db).nextRunAt,due+6*3600000);
  run(db,"UPDATE tasks SET status='completed' WHERE id=? OR parent_id=?",scan.id,scan.id);
  // An interrupted next-run update must not create another scan after restart.
  const settings=knowledgeSettings(db);settings.nextRunAt=0;run(db,"UPDATE settings SET value=? WHERE key='company_intelligence'",JSON.stringify(settings));
  assert.equal(scanKnowledgeIfDue(db,version,due+1000),null);
  saveKnowledgeSettings(db,{enabled:false,intervalHours:6,groups},'owner',due);
  assert.equal(scanKnowledgeIfDue(db,version,due+12*3600000),null);
  console.log('PASS source scope, full answers, replay acknowledgement, and durable scan scheduling');
} finally {db.close();rmSync(dir,{recursive:true,force:true});}
