import { spawn } from 'node:child_process';
import { mkdtempSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
const root=path.join(path.dirname(fileURLToPath(import.meta.url)),'..');
const data=mkdtempSync(path.join(os.tmpdir(),'rei-smoke-'));
const child=spawn(process.execPath,['hub.mjs'],{cwd:root,env:{...process.env,REI_DATA_DIR:data,REI_PORT:'4181'},stdio:['ignore','pipe','pipe']});
let output='';child.stdout.on('data',chunk=>output+=chunk);child.stderr.on('data',chunk=>output+=chunk);
try {
  for(let i=0;i<100&&!output.includes('REI Hub:');i++)await new Promise(r=>setTimeout(r,100));
  assert.match(output,/REI Hub:/);
  const setup=output.match(/\?setup=([^\s]+)/)[1];
  let cookie='';
  const api=async(route,data,auth)=>{const res=await fetch(`http://127.0.0.1:4181/api?route=${route}`,{method:data?'POST':'GET',headers:{...(data?{'content-type':'application/json'}:{}),...(cookie?{cookie}:{}),...(auth?{authorization:`Bearer ${auth}`}:{})},body:data?JSON.stringify(data):undefined});const body=await res.json();assert.ok(res.ok,`${route}: ${res.status} ${JSON.stringify(body)}`);if(res.headers.get('set-cookie'))cookie=res.headers.get('set-cookie').split(';')[0];return body;};
  await api('setup/complete',{token:setup,username:'owner',password:'smoke-test-password-123'});
  await api('auth/login',{username:'owner',password:'smoke-test-password-123'});
  const saved=await api('backup/create',{});
  assert.ok(saved.folder.startsWith(data));
  const enrolled=await api('devices/enroll',{label:'test-mac',isPlanner:true});
  const auth=enrolled.token;
  await api('connector/heartbeat',{agentName:'rei',capabilities:['openclaw']},auth);
  assert.equal((await api('devices')).devices[0].agent_name,'rei');
  const mcp=await api('mcp/add',{label:'Test Calendar',url:'https://example.com/mcp',auth:'oauth',deviceId:enrolled.device.id});
  assert.match(mcp.name,/^rei_[a-f0-9]{12}$/);
  assert.equal((await api('mcp/list')).integrations[0].status,null);
  assert.equal((await api('connector/heartbeat',{capabilities:['openclaw'],mcpStatuses:[{name:mcp.name,status:'auth_required'}]},auth)).integrations[0].name,mcp.name);
  assert.equal((await api('mcp/list')).integrations[0].status,'auth_required');
  await api('mcp/check',{name:mcp.name});
  const check=(await api('connector/heartbeat',{capabilities:['openclaw']},auth)).checks[0];
  assert.equal(check.name,mcp.name);
  await api('connector/mcp-check-result',{name:mcp.name,requestId:check.request_id,status:'auth_required',toolCount:0,error:'OAuthが必要'},auth);
  assert.equal((await api('mcp/list')).integrations[0].check_status,'auth_required');
  await api('mcp/check',{name:mcp.name});
  const nextCheck=(await api('connector/heartbeat',{capabilities:['openclaw']},auth)).checks[0];
  await api('connector/mcp-check-result',{name:mcp.name,requestId:nextCheck.request_id,status:'success',toolCount:3,error:''},auth);
  assert.equal((await api('mcp/list')).integrations[0].tool_count,3);
  const batch=await api('mcp/add-batch',{deviceId:enrolled.device.id,ids:['freee','moneyforward-accounting','misoca','kintone-docs']});
  assert.equal(batch.integrations.length,4);
  assert.ok(batch.integrations.every(item=>item.added));
  assert.equal((await api('mcp/add-batch',{deviceId:enrolled.device.id,ids:['freee']})).integrations[0].added,false);
  assert.equal((await api('connector/heartbeat',{capabilities:['openclaw']},auth)).integrations.length,5);
  const pairing=await api('devices/pairing',{label:'remote-mac'});
  const paired=await api('connector/pair',{code:pairing.code});
  assert.equal(paired.device.label,'remote-mac');
  await api('connector/heartbeat',{capabilities:['openclaw']},paired.token);
  assert.equal((await api('connector/heartbeat',{capabilities:['openclaw']},paired.token)).integrations.length,0);
  await api('mcp/remove',{name:mcp.name});
  for(const item of batch.integrations)await api('mcp/remove',{name:item.name});
  assert.equal((await api('mcp/list')).integrations.length,0);
  const replay=await fetch('http://127.0.0.1:4181/api?route=connector%2Fpair',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:pairing.code})});
  assert.equal(replay.status,403);
  const project=(await api('projects/create',{name:'新規事業',objective:'最初の成果を作る'})).project;
  assert.equal((await api('bootstrap')).projects[0].name,'新規事業');
  const created=await api('command',{text:'テスト用の仕事をして',department:'operations',projectId:project.id});
  assert.equal(created.task.projectId,project.id);
  const plan=await api('connector/claim',{},auth);assert.equal(plan.job.kind,'plan');
  assert.equal(plan.job.project.objective,'最初の成果を作る');
  await api('connector/result',{taskId:plan.job.id,leaseId:plan.job.lease_id,success:true,result:JSON.stringify({steps:[{prompt:'一つ目を実行',deviceId:enrolled.device.id}]})},auth);
  const execute=await api('connector/claim',{},auth);assert.equal(execute.job.kind,'execute');
  assert.equal(execute.job.project_id,project.id);
  assert.equal(execute.job.project.name,'新規事業');
  await api('connector/result',{taskId:execute.job.id,leaseId:execute.job.lease_id,success:true,result:'一つ目が完了'},auth);
  const bootstrap=await api('bootstrap');assert.equal(bootstrap.tasks[0].status,'completed');
  assert.equal(bootstrap.projects[0].completed,1);
  const detail=await api(`tasks/detail/${created.task.id}`);
  assert.equal(detail.children.length,2);
  assert.ok(detail.events.some(item=>item.type==='planned'));
  assert.equal(detail.canCancel,false);
  const stopped=(await api('command',{text:'中止する仕事'})).task;
  assert.equal((await api(`tasks/detail/${stopped.id}`)).canCancel,true);
  await api('tasks/cancel',{taskId:stopped.id});
  assert.equal((await api(`tasks/detail/${stopped.id}`)).task.status,'cancelled');
  const cancelledAgain=await fetch('http://127.0.0.1:4181/api?route=tasks%2Fcancel',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({taskId:stopped.id})});
  assert.equal(cancelledAgain.status,409);
  const human=(await api('command',{text:'担当者に確認する'})).task;
  const humanPlan=(await api('connector/claim',{},auth)).job;
  await api('connector/result',{taskId:humanPlan.id,leaseId:humanPlan.lease_id,success:true,result:JSON.stringify({steps:[{prompt:'担当者の回答を待つ',human:true,department:'people'}]})},auth);
  const humanStep=(await api(`tasks/detail/${human.id}`)).children.find(item=>item.kind==='human');
  assert.equal(humanStep.status,'waiting_human');
  assert.ok((await api('bootstrap')).humanPending.includes(human.id));
  await api('human/respond',{taskId:humanStep.id,answer:'担当者が了承しました'});
  assert.equal((await api(`tasks/detail/${human.id}`)).task.status,'completed');
  assert.ok(!(await api('bootstrap')).humanPending.includes(human.id));
  const repliedAgain=await fetch('http://127.0.0.1:4181/api?route=human%2Frespond',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({taskId:humanStep.id,answer:'重複'})});
  assert.equal(repliedAgain.status,409);
  await api('projects/status',{projectId:project.id,status:'paused'});
  const paused=await fetch('http://127.0.0.1:4181/api?route=command',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({text:'保留中の依頼',projectId:project.id})});
  assert.equal(paused.status,400);
  await api('projects/status',{projectId:project.id,status:'active'});
  const report=await api('report/today');assert.equal(report.completed,2);
  assert.ok(report.devices.find(device=>device.id===enrolled.device.id).completed>=3);
  assert.equal(report.people.completed,1);
  const invite=await api('users/invite',{role:'requester'});
  await api('setup/complete',{token:invite.token,username:'requester',password:'requester-password-123'});
  await api('auth/login',{username:'requester',password:'requester-password-123'});
  const requesterCookie=cookie;
  const forbiddenUsers=await fetch('http://127.0.0.1:4181/api?route=users%2Flist',{headers:{cookie}});
  assert.equal(forbiddenUsers.status,403);
  const blockedBackup=await fetch('http://127.0.0.1:4181/api?route=backup%2Fcreate',{method:'POST',headers:{cookie,'content-type':'application/json'},body:'{}'});
  assert.equal(blockedBackup.status,403);
  const forbidden=await fetch('http://127.0.0.1:4181/api?route=projects%2Fcreate',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({name:'不可',objective:'不可'})});
  assert.equal(forbidden.status,403);
  const gated=await api('command',{text:'承認が必要な依頼',department:'operations'});
  assert.equal(gated.task.status,'approval_pending');
  await api('auth/login',{username:'owner',password:'smoke-test-password-123'});
  const member=(await api('users/list')).users.find(user=>user.username==='requester');
  assert.equal(member.role,'requester');
  await api('users/role',{userId:member.id,role:'viewer'});
  assert.equal((await api('users/list')).users.find(user=>user.id===member.id).role,'viewer');
  const viewerCommand=await fetch('http://127.0.0.1:4181/api?route=command',{method:'POST',headers:{cookie:requesterCookie,'content-type':'application/json'},body:JSON.stringify({text:'実行できない指示'})});
  assert.equal(viewerCommand.status,403);
  await api('users/disable',{userId:member.id,disabled:true});
  assert.equal((await api('users/list')).users.find(user=>user.id===member.id).disabled,1);
  const stoppedSession=await fetch('http://127.0.0.1:4181/api?route=auth%2Fme',{headers:{cookie:requesterCookie}});
  assert.equal(stoppedSession.status,401);
  const disabledLogin=await fetch('http://127.0.0.1:4181/api?route=auth%2Flogin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'requester',password:'requester-password-123'})});
  assert.equal(disabledLogin.status,401);
  await api('users/disable',{userId:member.id,disabled:false});
  await api('users/role',{userId:member.id,role:'requester'});
  await api('tasks/approve',{taskId:gated.task.id});
  const approved=(await api('bootstrap')).tasks.find(t=>t.id===gated.task.id);
  assert.equal(approved.status,'planning');
  await api('auth/password',{currentPassword:'smoke-test-password-123',newPassword:'new-smoke-password-123'});
  await api('auth/logout',{});
  await api('auth/login',{username:'owner',password:'new-smoke-password-123'});
  assert.equal((await api('auth/me')).user.username,'owner');
  await api('connector/heartbeat',{agentName:'rei',capabilities:['openclaw','planning']},paired.token);
  assert.equal((await api('connector/claim',{},paired.token)).job,null);
  const testDb=new DatabaseSync(path.join(data,'rei.sqlite'));
  testDb.prepare('UPDATE devices SET last_seen=0 WHERE id=?').run(enrolled.device.id);
  testDb.close();
  const failoverState=await api('bootstrap');
  assert.equal(failoverState.workers.find(worker=>worker.id===enrolled.device.id).connected,false);
  assert.ok(failoverState.workers.find(worker=>worker.id===paired.device.id).capabilities.includes('planning'));
  const fallback=(await api('connector/claim',{},paired.token)).job;
  assert.equal(fallback.kind,'plan');
  assert.equal(fallback.parent_id,gated.task.id);
  await api('connector/result',{taskId:fallback.id,leaseId:fallback.lease_id,success:true,result:JSON.stringify({steps:[{prompt:'予備端末で実行',deviceId:paired.device.id}]})},paired.token);
  const fallbackStep=(await api('connector/claim',{},paired.token)).job;
  assert.equal(fallbackStep.kind,'execute');
  await api('connector/result',{taskId:fallbackStep.id,leaseId:fallbackStep.lease_id,success:true,result:'予備端末で完了'},paired.token);
  assert.equal((await api(`tasks/detail/${gated.task.id}`)).task.status,'completed');
  const stranded=(await api('command',{text:'停止中PCの未着手仕事'})).task;
  const strandedPlan=(await api('connector/claim',{},paired.token)).job;
  await api('connector/result',{taskId:strandedPlan.id,leaseId:strandedPlan.lease_id,success:true,result:JSON.stringify({steps:[{prompt:'別PCへ移す仕事',deviceId:enrolled.device.id}]})},paired.token);
  const strandedStep=(await api(`tasks/detail/${stranded.id}`)).children.find(step=>step.kind==='execute');
  assert.equal(strandedStep.assignedDeviceId,enrolled.device.id);
  assert.equal((await api('connector/claim',{},paired.token)).job,null);
  await api('tasks/reassign',{taskId:strandedStep.id,deviceId:paired.device.id});
  const reassigned=(await api('connector/claim',{},paired.token)).job;
  assert.equal(reassigned.id,strandedStep.id);
  const lateReassign=await fetch('http://127.0.0.1:4181/api?route=tasks%2Freassign',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({taskId:reassigned.id,deviceId:paired.device.id})});
  assert.equal(lateReassign.status,409);
  await api('connector/result',{taskId:reassigned.id,leaseId:reassigned.lease_id,success:true,result:'移動後に完了'},paired.token);
  assert.equal((await api(`tasks/detail/${stranded.id}`)).task.status,'completed');
  const retryable=(await api('command',{text:'計画失敗後の復旧'})).task;
  const failedPlan=(await api('connector/claim',{},paired.token)).job;
  assert.equal(failedPlan.kind,'plan');
  await api('connector/result',{taskId:failedPlan.id,leaseId:failedPlan.lease_id,success:false,error:'モデルが応答しなかった'},paired.token);
  const failedDetail=await api(`tasks/detail/${retryable.id}`);
  assert.equal(failedDetail.task.status,'needs_review');
  assert.equal(failedDetail.canRetryPlan,true);
  await api('tasks/retry-plan',{taskId:retryable.id});
  assert.equal((await api(`tasks/detail/${retryable.id}`)).task.status,'planning');
  const duplicateRetry=await fetch('http://127.0.0.1:4181/api?route=tasks%2Fretry-plan',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({taskId:retryable.id})});
  assert.equal(duplicateRetry.status,409);
  const retriedPlan=(await api('connector/claim',{},paired.token)).job;
  assert.equal(retriedPlan.id,failedPlan.id);
  await api('connector/result',{taskId:retriedPlan.id,leaseId:retriedPlan.lease_id,success:true,result:JSON.stringify({steps:[{prompt:'再計画した仕事',deviceId:paired.device.id}]})},paired.token);
  const retriedStep=(await api('connector/claim',{},paired.token)).job;
  await api('connector/result',{taskId:retriedStep.id,leaseId:retriedStep.lease_id,success:true,result:'復旧後に完了'},paired.token);
  const recovered=await api(`tasks/detail/${retryable.id}`);
  assert.equal(recovered.task.status,'completed');
  assert.ok(recovered.events.some(item=>item.type==='plan_retried'));
  const malformed=(await api('command',{text:'計画の形式が崩れた場合'})).task;
  const malformedPlan=(await api('connector/claim',{},paired.token)).job;
  await api('connector/result',{taskId:malformedPlan.id,leaseId:malformedPlan.lease_id,success:true,result:'JSONではない文章'},paired.token);
  const malformedDetail=await api(`tasks/detail/${malformed.id}`);
  assert.equal(malformedDetail.task.status,'needs_review');
  assert.equal(malformedDetail.children.length,1);
  assert.equal(malformedDetail.canRetryPlan,true);
  assert.equal((await api('connector/claim',{},paired.token)).job,null);
  const unknownDevice=(await api('command',{text:'存在しないPCへの割当'})).task;
  const unknownPlan=(await api('connector/claim',{},paired.token)).job;
  await api('connector/result',{taskId:unknownPlan.id,leaseId:unknownPlan.lease_id,success:true,result:JSON.stringify({steps:[{prompt:'指定PCだけで処理',deviceId:'00000000-0000-4000-8000-000000000000'}]})},paired.token);
  const unknownDetail=await api(`tasks/detail/${unknownDevice.id}`);
  assert.equal(unknownDetail.task.status,'needs_review');
  assert.equal(unknownDetail.children.length,1);
  assert.match(unknownDetail.task.error,/担当PC/);
  const tooMany=(await api('command',{text:'工程数の上限確認'})).task;
  const tooManyPlan=(await api('connector/claim',{},paired.token)).job;
  await api('connector/result',{taskId:tooManyPlan.id,leaseId:tooManyPlan.lease_id,success:true,result:JSON.stringify({steps:Array.from({length:13},(_,index)=>({prompt:`工程${index+1}`}))})},paired.token);
  assert.equal((await api(`tasks/detail/${tooMany.id}`)).children.length,1);
  assert.equal((await api(`tasks/detail/${tooMany.id}`)).task.status,'needs_review');
  const uncertain=(await api('command',{text:'通信切断後の結果確認'})).task;
  const uncertainPlan=(await api('connector/claim',{},paired.token)).job;
  await api('connector/result',{taskId:uncertainPlan.id,leaseId:uncertainPlan.lease_id,success:true,result:JSON.stringify({steps:[{prompt:'結果を確認する作業',deviceId:paired.device.id}]})},paired.token);
  const uncertainStep=(await api('connector/claim',{},paired.token)).job;
  const staleDb=new DatabaseSync(path.join(data,'rei.sqlite'));
  staleDb.prepare('UPDATE tasks SET lease_until=? WHERE id=?').run(Date.now()-1,uncertainStep.id);
  staleDb.close();
  assert.equal((await api('bootstrap')).tasks.find(task=>task.id===uncertain.id).status,'needs_review');
  assert.equal((await api(`tasks/detail/${uncertain.id}`)).children.find(step=>step.id===uncertainStep.id).status,'needs_review');
  await api('tasks/reconcile',{taskId:uncertainStep.id,resolution:'completed',note:'端末で成果物を確認した'});
  const reconciled=await api(`tasks/detail/${uncertain.id}`);
  assert.equal(reconciled.task.status,'completed');
  assert.ok(reconciled.events.some(item=>item.type==='reconciled'));
  const secondReconcile=await fetch('http://127.0.0.1:4181/api?route=tasks%2Freconcile',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({taskId:uncertainStep.id,resolution:'completed',note:'重複'})});
  assert.equal(secondReconcile.status,409);
  await api('connector/heartbeat',{agentName:'rei',capabilities:['openclaw','planning','execution']},auth);
  const parallel=(await api('command',{text:'独立した二つの仕事'})).task;
  const parallelPlan=(await api('connector/claim',{},auth)).job;
  await api('connector/result',{taskId:parallelPlan.id,leaseId:parallelPlan.lease_id,success:true,result:JSON.stringify({steps:[{prompt:'独立した仕事A'},{prompt:'独立した仕事B'}]})},auth);
  const [firstClaim,secondClaim]=await Promise.all([api('connector/claim',{},auth),api('connector/claim',{},paired.token)]);
  assert.equal(firstClaim.job.kind,'execute');
  assert.equal(secondClaim.job.kind,'execute');
  assert.notEqual(firstClaim.job.id,secondClaim.job.id);
  await Promise.all([
    api('connector/result',{taskId:firstClaim.job.id,leaseId:firstClaim.job.lease_id,success:true,result:'A完了'},auth),
    api('connector/result',{taskId:secondClaim.job.id,leaseId:secondClaim.job.lease_id,success:true,result:'B完了'},paired.token)
  ]);
  assert.equal((await api(`tasks/detail/${parallel.id}`)).task.status,'completed');
  const historyDb=new DatabaseSync(path.join(data,'rei.sqlite'));
  const inserted=historyDb.prepare("INSERT INTO tasks(id,kind,text,status,result,created_at) VALUES(?,'root',?,'completed',?,?)");
  for(let index=0;index<105;index++)inserted.run(`00000000-0000-4000-8000-${String(index).padStart(12,'0')}`,`履歴${index}`,'x'.repeat(6000),Date.now());
  historyDb.close();
  const latest=await api('bootstrap');
  assert.equal(latest.tasks.length,100);
  assert.equal(latest.hasOlderTasks,true);
  assert.ok(latest.tasks.every(task=>task.result.length<=500));
  const cursor=latest.tasks.at(-1);
  const older=await api('tasks/history',{beforeTime:Date.parse(cursor.createdAt),beforeId:cursor.id});
  assert.ok(older.tasks.length>0);
  assert.equal(new Set([...latest.tasks,...older.tasks].map(task=>task.id)).size,latest.tasks.length+older.tasks.length);
  assert.equal((await api(`tasks/detail/${latest.tasks[0].id}`)).task.result.length,6000);
  console.log('PASS setup/login/enroll/plan/dispatch/result/report');
} finally {child.kill('SIGTERM');}
