import { mkdtempSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { openStorage, run } from '../storage.mjs';
import { report } from '../workflow.mjs';

const dir=mkdtempSync(path.join(os.tmpdir(),'rei-report-'));
process.env.REI_DATA_DIR=dir;
const db=openStorage(dir);
const day=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const start=new Date(`${day}T00:00:00+09:00`).getTime();
const yesterday=start-60_000,today=start+60_000;
const deviceId='00000000-0000-4000-8000-000000000001';
run(db,'INSERT INTO devices(id,label,token_hash) VALUES(?,?,?)',deviceId,'前日から稼働したPC','test-hash');
run(db,'INSERT INTO projects(id,name,objective,created_at,updated_at) VALUES(?,?,?,?,?)','project-report','顧客Aの案件','状況共有',yesterday,yesterday);
run(db,'INSERT INTO tasks(id,kind,text,status,created_at,finished_at) VALUES(?,?,?,?,?,?)','root-today','root','前日から今日まで','completed',yesterday,today);
run(db,'INSERT INTO tasks(id,kind,text,status,created_at,finished_at) VALUES(?,?,?,?,?,?)','root-old','root','前日だけ','completed',yesterday,yesterday);
run(db,'INSERT INTO tasks(id,kind,text,status,error,created_at,finished_at) VALUES(?,?,?,?,?,?,?)','root-old-review','root','前日から未解決','needs_review','結果を確認',yesterday,yesterday);
run(db,'INSERT INTO tasks(id,kind,text,status,error,created_at,finished_at) VALUES(?,?,?,?,?,?,?)','root-today-review','root','今日の要確認','needs_review','今日の結果を確認',today,today);
run(db,'INSERT INTO tasks(id,kind,text,status,error,created_at,finished_at) VALUES(?,?,?,?,?,?,?)','root-today-failed','root','今日の失敗','failed','確認済みの失敗',today,today);
run(db,'INSERT INTO tasks(id,kind,text,status,created_at) VALUES(?,?,?,?,?)','root-old-approval','root','前日から承認待ち','approval_pending',yesterday);
run(db,'INSERT INTO tasks(id,parent_id,kind,text,status,device_id,created_at,started_at,finished_at) VALUES(?,?,?,?,?,?,?,?,?)','device-today','root-today','execute','PCの工程','completed',deviceId,yesterday,yesterday,today);
run(db,'INSERT INTO tasks(id,parent_id,kind,text,status,error,device_id,created_at,started_at,finished_at) VALUES(?,?,?,?,?,?,?,?,?,?)','device-failed','root-today-failed','execute','失敗した工程','failed','実行失敗',deviceId,today,today,today);
run(db,'INSERT INTO tasks(id,parent_id,kind,text,status,created_at,finished_at) VALUES(?,?,?,?,?,?,?)','human-today','root-today','human','人の回答','completed',yesterday,today);
run(db,"UPDATE tasks SET project_id=? WHERE id IN ('root-today','root-old-review','root-old-approval')",'project-report');
const result=report(db);
assert.equal(result.total,3);
assert.equal(result.completed,1);
assert.equal(result.failed,1);
assert.equal(result.interrupted,1);
assert.equal(result.tasks.find(task=>task.id==='root-today').activityAt,new Date(today).toISOString());
assert.equal(result.tasks.find(task=>task.id==='root-today').projectName,'顧客Aの案件');
assert.equal(result.attentionBacklog.tasks[0].projectName,'顧客Aの案件');
assert.equal(result.approvalBacklog.total,1);
assert.equal(result.approvalBacklog.tasks[0].id,'root-old-approval');
assert.equal(result.approvalBacklog.tasks[0].projectName,'顧客Aの案件');
assert.equal(result.devices[0].completed,1);
assert.equal(result.devices[0].failed,1);
assert.equal(result.devices[0].attention,0);
assert.equal(result.people.completed,1);
assert.equal(result.attentionBacklog.total,1);
assert.equal(result.attentionBacklog.tasks[0].id,'root-old-review');
db.close();
console.log('PASS overnight work appears in the day it completes');
